version: '3.8'

services:
  backend:
    image: abhi0565/order-backendapp:v1
    container_name: order-backend
    volumes:
      - ./Order-Management/src/main/resources/application.properties:/app/application.properties:ro
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/ecom_db?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Bksra99@
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8080:8080"
    networks:
      - ecom-network

  frontend:
    image: ecom-frontend:latest
    container_name: order-frontend
    volumes:
      - ./ecommerceorder-frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ecommerceorder-frontend/dist/ecommerceorder-frontend/browser:/usr/share/nginx/html/browser:ro
    ports:
      - "4200:80"
    networks:
      - ecom-network

networks:
  ecom-network:
    driver: bridge
